services:
  postgres-token-bot:
    image: postgres:15
    container_name: bot_service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PG_HBA_CONF: |
        host  all  all  0.0.0.0/0  trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5431}:5432'

  redis-token-bot:
    image: redis:7-alpine
    container_name: bot_service_redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data

  pgadmin-token-bot:
    image: dpage/pgadmin4:latest
    container_name: bot_service_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      - postgres-token-bot

volumes:
  postgres_data:
  redis_data:
